# Generated by Django 5.2.8 on 2025-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Humidity')),
                ('co2', models.FloatField(verbose_name='CO2')),
                ('noise', models.FloatField(verbose_name='Noise level')),
                ('light', models.FloatField(verbose_name='Light level')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
